Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 27, in btn_command
    self.var.set(self.command())
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 40, in ofg_name
    return filedialog.askopenfilename(filetypes=self.ext)
  File "C:\Program Files\Python39\lib\tkinter\filedialog.py", line 382, in askopenfilename
    return Open(**options).show()
  File "C:\Program Files\Python39\lib\tkinter\commondialog.py", line 46, in show
    s = w.tk.call(self.command, *w._options(self.options))
_tkinter.TclError: bad file type ".csv", should be "typeName {extension ?extensions ...?} ?{macType ?macTypes ...?}?"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 27, in btn_command
    self.var.set(self.command())
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 40, in ofg_name
    return filedialog.askopenfilename(filetypes=self.ext)
  File "C:\Program Files\Python39\lib\tkinter\filedialog.py", line 382, in askopenfilename
    return Open(**options).show()
  File "C:\Program Files\Python39\lib\tkinter\commondialog.py", line 46, in show
    s = w.tk.call(self.command, *w._options(self.options))
_tkinter.TclError: bad file type ".csv", should be "typeName {extension ?extensions ...?} ?{macType ?macTypes ...?}?"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 27, in btn_command
    self.var.set(self.command())
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 40, in ofg_name
    return filedialog.askopenfilename(filetypes=self.ext)
  File "C:\Program Files\Python39\lib\tkinter\filedialog.py", line 382, in askopenfilename
    return Open(**options).show()
  File "C:\Program Files\Python39\lib\tkinter\commondialog.py", line 46, in show
    s = w.tk.call(self.command, *w._options(self.options))
_tkinter.TclError: bad file type ".csv", should be "typeName {extension ?extensions ...?} ?{macType ?macTypes ...?}?"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 27, in btn_command
    self.var.set(self.command())
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 40, in ofg_name
    return filedialog.askopenfilename(filetypes=self.ext)
  File "C:\Program Files\Python39\lib\tkinter\filedialog.py", line 382, in askopenfilename
    return Open(**options).show()
  File "C:\Program Files\Python39\lib\tkinter\commondialog.py", line 46, in show
    s = w.tk.call(self.command, *w._options(self.options))
_tkinter.TclError: bad file type ".csv", should be "typeName {extension ?extensions ...?} ?{macType ?macTypes ...?}?"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 27, in btn_command
    self.var.set(self.command())
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 40, in ofg_name
    return filedialog.askopenfilename(filetypes=self.ext)
  File "C:\Program Files\Python39\lib\tkinter\filedialog.py", line 382, in askopenfilename
    return Open(**options).show()
  File "C:\Program Files\Python39\lib\tkinter\commondialog.py", line 46, in show
    s = w.tk.call(self.command, *w._options(self.options))
_tkinter.TclError: bad file type ".csv", should be "typeName {extension ?extensions ...?} ?{macType ?macTypes ...?}?"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 27, in btn_command
    self.var.set(self.command())
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 40, in ofg_name
    return filedialog.askopenfilename(filetypes=self.ext)
  File "C:\Program Files\Python39\lib\tkinter\filedialog.py", line 382, in askopenfilename
    return Open(**options).show()
  File "C:\Program Files\Python39\lib\tkinter\commondialog.py", line 46, in show
    s = w.tk.call(self.command, *w._options(self.options))
_tkinter.TclError: bad file type ".csv", should be "typeName {extension ?extensions ...?} ?{macType ?macTypes ...?}?"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 27, in btn_command
    self.var.set(self.command())
  File "C:\Users\Xavier\trav\tableurs\290521\ui.py", line 40, in ofg_name
    return filedialog.askopenfilename(filetypes=self.ext)
  File "C:\Program Files\Python39\lib\tkinter\filedialog.py", line 382, in askopenfilename
    return Open(**options).show()
  File "C:\Program Files\Python39\lib\tkinter\commondialog.py", line 46, in show
    s = w.tk.call(self.command, *w._options(self.options))
_tkinter.TclError: bad file type ".csv", should be "typeName {extension ?extensions ...?} ?{macType ?macTypes ...?}?"
